### ISSUE TITLE
What happened to this project?

### ISSUE THREAD

**Issue by Zero3K** [umjammer/vavi-sound#13]
*subject*

**Comment by umjammer** [comment]
what do u mean?

is still under construction? yes.
but mostly my goals have been done. so currently i don't touch.

---

this is an issue tracker.
if u have any request to this project, use "Discussions" please.

**Comment by Zero3K** [comment]
> what do u mean?
> 
> is still under construction? yes. but mostly my goals have been done. so currently i don't touch.

What about the TODO section in its Readme?

**Comment by umjammer** [comment]
about "receiver" and "ssrc", both are internal architecture issues not about functionality.
and "wip at vavi-sound-sandbox" was canceled. those have already been done in this project. (the document was not updated)

so i said mostly done.
i mean there are no plans to update for a while.
